name: Movies App - CI/CD Workflow - Push => ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

env:
  VITE_ENV: "production"
  VITE_BASE_URL: "/"
  VITE_API_HOST: "https://api.themoviedb.org/3"
  VITE_TMDB_TOKEN: "${{ secrets.VITE_TMDB_TOKEN }}"

jobs:
  analyze-code:
    name: Analyze Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Lint
        run: pnpm run lint:check

      - name: Check Typing
        run: pnpm run type-check

      - name: Message Success
        run: echo "Code was analyzed successfuly for branch '${{ github.ref_name }}'"

  test-code:
    name: Test Code
    needs: [analyze-code]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Run unit tests
        run: pnpm run test:unit:ci

      - name: Install playwright browsers
        run: pnpm run test:e2e:install

      - name: Run end-to-end tests
        run: pnpm run test:e2e:ci

      - name: Message Success
        run: echo "Code was tested successfuly for branch '${{ github.ref_name }}'"

  generate-changelog:
    name: Generate CHANGELOG.md
    needs: [test-code]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node

      - name: Message Info
        run: echo "Pull Request to generate CHANGELOG.md was triggered for branch '${{ github.ref_name }}'"
