name: Movies App - CI/CD Workflow - Push

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-code:
    name: Analyze Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Last Commit from Push
        run: pnpm run commit:check:last

      - name: Check Lint
        run: pnpm run lint:check

      - name: Check Typing
        run: pnpm run type-check

      - name: Message Success
        run: echo "Code was analyzed successfuly for branch '${{ github.ref_name }}'"

  test-code:
    name: Test Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Run unit tests
        run: pnpm run test:unit:ci

      - name: Install playwright browsers
        run: pnpm run test:e2e:install

      - name: Run end-to-end tests
        run: pnpm run test:e2e:ci

      - name: Message Success
        run: echo "Code was tested successfuly for branch '${{ github.ref_name }}'"

  generate-release:
    name: Generate Release
    needs: [analyze-code, test-code]
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Create Release
        uses: codfish/semantic-release-action@v3
        with:
          dry_run: false
          additional-packages: [
            "conventional-changelog-conventionalcommits@7",
            "@semantic-release/changelog",
            "@semantic-release/git"
          ]
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'master',
              'main',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              [
                "@semantic-release/release-notes-generator",
                {
                  "preset": "conventionalcommits",
                  "presetConfig": {
                    "types": [
                      { type: 'feat', section: 'Features', hidden: false },
                      { type: 'fix', section: 'Bug Fixes', hidden: false },
                      { type: 'perf', section: 'Performance Improvements', hidden: false },
                      { type: 'revert', section: 'Reverts', hidden: false },
                      { type: 'docs', section: 'Other Updates', hidden: false },
                      { type: 'style', section: 'Other Updates', hidden: false },
                      { type: 'chore', section: 'Other Updates', hidden: false },
                      { type: 'refactor', section: 'Other Updates', hidden: false },
                      { type: 'test', section: 'Other Updates', hidden: false },
                      { type: 'build', section: 'Other Updates', hidden: false },
                      { type: 'ci', section: 'Other Updates', hidden: false }
                    ]
                  }
                }
              ],
              "@semantic-release/changelog",
              "@semantic-release/git"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Message Success
        run:  echo "Release ${{ steps.semantic.outputs.release-version }} was generated successfuly"
